import SliderImage from '@/components/oglašivači/sliderImage/SliderImage';
import Link from 'next/link';
import React from 'react'

const OglašivačiDesktopSliderOne = () => {
  return (
    <div className="desktop-slider__box">
      <div className="desktop-slider__flex">
        <Link
          href="https://posao.zaposlise.hr/profile/company/OGANJ-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/10/Zaposlise-poslodavac-Oganj.png"
            alt="oganj"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Carwiz-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/09/carwiz.png"
            alt="carwiz"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/SPORT-VISION-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/09/sportvision.png"
            alt="sportvision"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Orto-Rea-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/09/zaposlise-poslodavac-ortorea@2x.png"
            alt="ortorea"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Frigooprema-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/09/zaposlise-poslodavac-frigooprema@2x.png"
            alt="frigo-oprema"
            loading="lazy"
          />
        </Link>
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/revuto-logo-2.png"
          alt="revuto"
          loading="lazy"
        />
        <Link
          href="https://posao.zaposlise.hr/profile/company/Duplico-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/07/duplico-logo-2.png"
            alt="duplico"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Groupama-osiguranje-d.d"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/11/groupama-zaposlise-poslodavac@2x.png"
            alt="groupama"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/PRO-KLIMA-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/11/pro-klima-zaposlise-poslodavac@2x.png"
            alt="pro-klima"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/R%C3%B6fix-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/11/roefix-zaposlise-poslodavac@2x.png"
            alt=""
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/AS-Kramar-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/12/as-kramar-zaposlise-poslodavac.png"
            alt="as-kramar"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Klimaoprema-d.d"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/12/klimaoprema-zaposlise-poslodavac.png"
            alt="klima-oprema"
            loading="lazy"
          />
        </Link>
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/12/wuerth-zaposlise-poslodavac.png"
          alt="wuerth"
          loading="lazy"
        />
        <Link
          href="https://posao.zaposlise.hr/profile/company/ABSTRACTO-STUDIO-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/10/abstracto_studio_logo.png"
            alt="abstract studio"
            loading="lazy"
          />
        </Link>
      </div>

      <div className="desktop-slider__flex">
        <Link
          href="https://posao.zaposlise.hr/profile/company/OGANJ-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/10/Zaposlise-poslodavac-Oganj.png"
            alt="oganj"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Carwiz-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/09/carwiz.png"
            alt="carwiz"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/SPORT-VISION-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/09/sportvision.png"
            alt="sportvision"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Orto-Rea-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/09/zaposlise-poslodavac-ortorea@2x.png"
            alt="ortorea"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Frigooprema-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/09/zaposlise-poslodavac-frigooprema@2x.png"
            alt="frigo-oprema"
            loading="lazy"
          />
        </Link>
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/revuto-logo-2.png"
          alt="revuto"
          loading="lazy"
        />
        <Link
          href="https://posao.zaposlise.hr/profile/company/Duplico-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/07/duplico-logo-2.png"
            alt="duplico"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Groupama-osiguranje-d.d"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/11/groupama-zaposlise-poslodavac@2x.png"
            alt="groupama"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/PRO-KLIMA-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/11/pro-klima-zaposlise-poslodavac@2x.png"
            alt="pro-klima"
            loading="lazy"
            width={145}
            height={60}
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/R%C3%B6fix-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/11/roefix-zaposlise-poslodavac@2x.png"
            alt=""
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/AS-Kramar-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/12/as-kramar-zaposlise-poslodavac.png"
            alt="as-kramar"
            loading="lazy"
          />
        </Link>
        <Link
          href="https://posao.zaposlise.hr/profile/company/Klimaoprema-d.d"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/12/klimaoprema-zaposlise-poslodavac.png"
            alt="klima-oprema"
            loading="lazy"
          />
        </Link>
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/12/wuerth-zaposlise-poslodavac.png"
          alt="wuerth"
          loading="lazy"
        />
        <Link
          href="https://posao.zaposlise.hr/profile/company/ABSTRACTO-STUDIO-d.o.o"
          target="_blank"
        >
          <SliderImage
            src="https://zaposlise.hr/wp-content/uploads/2023/10/abstracto_studio_logo.png"
            alt="abstract studio"
            loading="lazy"
          />
        </Link>
      </div>
    </div>
  );
}

export default OglašivačiDesktopSliderOne