import React from "react";
import Link from "next/link";
import SliderImage from "../../sliderImage/SliderImage";

const MobileSliderBox = () => {
  return (
    <div className="mobile-slider__flex">
      <Link
        href="https://posao.zaposlise.hr/profile/company/OGANJ-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/10/Zaposlise-poslodavac-Oganj.png"
          alt="oganj"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Carwiz-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/carwiz.png"
          alt="carwiz"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/SPORT-VISION-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/sportvision.png"
          alt="sportvision"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Orto-Rea-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/zaposlise-poslodavac-ortorea@2x.png"
          alt="ortorea"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Frigooprema-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/zaposlise-poslodavac-frigooprema@2x.png"
          alt="frigo-oprema"
        />
      </Link>
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/07/revuto-logo-2.png"
        alt="revuto"
      />
      <Link
        href="https://posao.zaposlise.hr/profile/company/Duplico-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/duplico-logo-2.png"
          alt="duplico"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Groupama-osiguranje-d.d"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/11/groupama-zaposlise-poslodavac@2x.png"
          alt="groupama"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/PRO-KLIMA-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/11/pro-klima-zaposlise-poslodavac@2x.png"
          alt="pro-klima"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/R%C3%B6fix-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/11/roefix-zaposlise-poslodavac@2x.png"
          alt=""
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/AS-Kramar-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/12/as-kramar-zaposlise-poslodavac.png"
          alt="as-kramar"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Klimaoprema-d.d"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/12/klimaoprema-zaposlise-poslodavac.png"
          alt="klima-oprema"
        />
      </Link>
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/12/wuerth-zaposlise-poslodavac.png"
        alt="wuerth"
      />
      <Link
        href="https://posao.zaposlise.hr/profile/company/ABSTRACTO-STUDIO-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/10/abstracto_studio_logo.png"
          alt="abstract studio"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Kariera"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2024/01/kariera-logo1@2x.png"
          alt="kariera"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Inchoo-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2024/01/inchoo-logo1@2x.png"
          alt="inchoo"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Đuro-Đaković-Energy-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2024/01/duro-dakovic-logo1@2x.png"
          alt="duro-dakovic"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Meneghetti"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2024/01/meneghetti-logo1@2x.png"
          alt="meneghetti"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Links-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/links-logo-2_2.png"
          alt="links"
        />
      </Link>
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/07/kontra-logo-2.png"
        alt="kontra-logo"
      />
      <Link
        href="https://posao.zaposlise.hr/profile/company/Degordian"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/degordian-logo-2.png"
          alt="degordian"
        />
      </Link>
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/09/morgan-grey-agency@2x.png"
        alt="morgan-grey-agency"
      />
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/09/morgan-code@2x.png"
        alt="morgan-code.png"
      />
      <Link
        href="https://posao.zaposlise.hr/profile/company/Samoborček-EU-grupa"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/samoborcek-grupa@2x.png"
          alt="samoborcek-grupa"
        />
      </Link>
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/09/go2bim@2x.png"
        alt="go2bim"
      />
      <Link
        href="https://posao.zaposlise.hr/profile/company/LUSH-MANUFAKTURA-D.O.O"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/zaposlise-poslodavac-lush-transparent@2x.png"
          alt="lush"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/1-KLIK-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/1klik-hr@2x.png"
          alt="1klik"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Stemi-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/stemi-logo-2.png"
          alt="stemi"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/decking.hr"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/decking-logo-2.png"
          alt="decking"
        />
      </Link>
    </div>
  );
};

export default MobileSliderBox;
