import React from "react";
import Link from "next/link";
import SliderImage from "../../sliderImage/SliderImage";

const DesktopSliderBox = () => {
  return (
    <div className="desktop-slider__flex-two">
      <Link
        href="https://posao.zaposlise.hr/profile/company/Kariera"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2024/01/kariera-logo1@2x.png"
          alt="kariera"
          loading="lazy"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Inchoo-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2024/01/inchoo-logo1@2x.png"
          alt="inchoo"
          loading="lazy"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Đuro-Đaković-Energy-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2024/01/duro-dakovic-logo1@2x.png"
          alt="duro-dakovic"
          loading="lazy"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Meneghetti"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2024/01/meneghetti-logo1@2x.png"
          alt="meneghetti"
          loading="lazy"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Links-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/links-logo-2_2.png"
          alt="links"
          loading="lazy"
        />
      </Link>
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/07/kontra-logo-2.png"
        alt="kontra-logo"
        loading="lazy"
      />
      <Link
        href="https://posao.zaposlise.hr/profile/company/Degordian"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/degordian-logo-2.png"
          alt="degordian"
          loading="lazy"
        />
      </Link>
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/09/morgan-grey-agency@2x.png"
        alt="morgan-grey-agency"
        loading="lazy"
      />
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/09/morgan-code@2x.png"
        alt="morgan-code.png"
        loading="lazy"
      />
      <Link
        href="https://posao.zaposlise.hr/profile/company/Samoborček-EU-grupa"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/samoborcek-grupa@2x.png"
          alt="samoborcek-grupa"
          loading="lazy"
        />
      </Link>
      <SliderImage
        src="https://zaposlise.hr/wp-content/uploads/2023/09/go2bim@2x.png"
        alt="go2bim"
      />
      <Link
        href="https://posao.zaposlise.hr/profile/company/LUSH-MANUFAKTURA-D.O.O"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/zaposlise-poslodavac-lush-transparent@2x.png"
          alt="lush"
          loading="lazy"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/1-KLIK-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/09/1klik-hr@2x.png"
          alt="1klik"
          loading="lazy"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/Stemi-d.o.o"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/stemi-logo-2.png"
          alt="stemi"
          loading="lazy"
        />
      </Link>
      <Link
        href="https://posao.zaposlise.hr/profile/company/decking.hr"
        target="_blank"
      >
        <SliderImage
          src="https://zaposlise.hr/wp-content/uploads/2023/07/decking-logo-2.png"
          alt="decking"
          loading="lazy"
        />
      </Link>
    </div>
  );
};

export default DesktopSliderBox;
